### ISSUE TITLE
Fix Bug when running yarn test

### ISSUE THREAD

**Issue by pizzooid** [pizzooid/explorer-and-cyberconnected-dapps#7]
yarn test gives an error

**Comment by Qoyyuum** [comment]
Can you share the error message?

**Comment by Qoyyuum** [comment]
I ran `yarn test` and I got an error as well.

```
 ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from "d3-array";
                                                                                      ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import React from 'react';
    > 2 | import * as d3 from "d3";
        | ^
      3 |
      4 | class NetworkGraph extends React.Component {
      5 |     constructor(props) {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/NetworkGraph.js:2:1)
```

So the bug seems to be d3 related (unless you are referring a different error?).

An answer from stackoverflow suggests to downgrade but I would advise against it. [StackOverflow answer](https://stackoverflow.com/a/68461789)

I'll help investigate but this should be a low priority thing to tackle.

**Comment by pizzooid** [comment]
I agree
